name: pipeline-umi-amplicon
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python==3.6
  - snakemake-minimal
  - minimap2
  - samtools
  - seqkit
  - pysam
  - vsearch
  - varscan
  - medaka>=1.1.2
  - pip
  - pip:
    - catfishq
